// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'placeholder-key';

export const isDemoMode = !import.meta.env.VITE_SUPABASE_URL;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase: SupabaseClient<Database> = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});

/** Prefer Edge Functions; fall back to SECURITY DEFINER RPCs when none are deployed. */
export async function invokeFunction<T>(name: string, body?: Record<string, unknown>): Promise<T> {
  const { data, error } = await supabase.functions.invoke(name, body ? { body } : {});
  if (!error && data && typeof data === "object" && !("error" in (data as object) && (data as { error?: unknown }).error)) {
    return data as T;
  }

  const rpcName = name.replaceAll("-", "_");
  const args: Record<string, unknown> = { ...(body ?? {}) };
  if ("findMe" in args) {
    args.findme = args.findMe;
    delete args.findMe;
  }
  const { data: fallback, error: rpcError } = await supabase.rpc(rpcName as never, args as never);
  if (rpcError) {
    throw error ?? rpcError;
  }
  return fallback as T;
}